{
    "experiment_run": 1,
    "dataset": "BasicMotions",
    "validation_split": [3,1],
    "window": [0.4, 0.6, 0.8, 1],
    "trees": [1, 5, 10, 20, 40, 60, 80, 100],
    "max_depth": [0,1,2],
    "max_samples": 0.8,
    "n_jobs": 10,
    "random_state": 0
    
    # The other parameters of LCE can be added and modified in this configuration file (current=default values) 
    # Please see LCE API documentation: https://lce.readthedocs.io/en/latest/generated/lce.LCEClassifier.html
}